# Generated by Django 5.0.6 on 2024-06-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_viaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=150)),
                ('apmaterno', models.CharField(max_length=150)),
                ('rut', models.IntegerField(default=0)),
                ('ciudad', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('tipo_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_viajes')),
            ],
        ),
    ]
