# Generated by Django 5.0.6 on 2024-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
