# Generated by Django 5.0.6 on 2024-07-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contrato_cantidad_alumnos_contrato_monto_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Viajes',
            new_name='Tipo_Viaje',
        ),
    ]
